const SIDEBAR_COLLAPSED_WIDTH = 52;
const SIDEBAR_EXPANDED_WIDTH = 288;

export const SIDEBAR_DELTA = SIDEBAR_EXPANDED_WIDTH - SIDEBAR_COLLAPSED_WIDTH;
export const SIDE_PANEL_MIN_WIDTH = 288;
export const SIDE_PANEL_ANIMATION_DURATION = 500;
export const SIDE_PANEL_DEFAULT_WIDTH_RATIO = 0.5;
