/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutSettingsRouteImport } from './routes/_sidebar-layout.settings'
import { Route as SidebarLayoutChatLayoutRouteImport } from './routes/_sidebar-layout._chat-layout'
import { Route as SidebarLayoutSettingsIndexRouteImport } from './routes/_sidebar-layout.settings.index'
import { Route as SidebarLayoutChatLayoutIndexRouteImport } from './routes/_sidebar-layout._chat-layout.index'
import { Route as SidebarLayoutSettingsUsageRouteImport } from './routes/_sidebar-layout.settings.usage'
import { Route as SidebarLayoutSettingsProjectsRouteImport } from './routes/_sidebar-layout.settings.projects'
import { Route as SidebarLayoutSettingsProjectRouteImport } from './routes/_sidebar-layout.settings.project'
import { Route as SidebarLayoutSettingsMemoryRouteImport } from './routes/_sidebar-layout.settings.memory'
import { Route as SidebarLayoutSettingsGeneralRouteImport } from './routes/_sidebar-layout.settings.general'
import { Route as SidebarLayoutSettingsAnalyticsRouteImport } from './routes/_sidebar-layout.settings.analytics'
import { Route as SidebarLayoutChatLayoutChatIdRouteImport } from './routes/_sidebar-layout._chat-layout.$chatId'
import { Route as SidebarLayoutSettingsProjectIndexRouteImport } from './routes/_sidebar-layout.settings.project.index'
import { Route as SidebarLayoutSettingsProjectWorkflowRouteImport } from './routes/_sidebar-layout.settings.project.workflow'
import { Route as SidebarLayoutSettingsProjectTeamRouteImport } from './routes/_sidebar-layout.settings.project.team'
import { Route as SidebarLayoutSettingsProjectSlackRouteImport } from './routes/_sidebar-layout.settings.project.slack'
import { Route as SidebarLayoutSettingsProjectModelsRouteImport } from './routes/_sidebar-layout.settings.project.models'
import { Route as SidebarLayoutSettingsProjectMcpServersRouteImport } from './routes/_sidebar-layout.settings.project.mcp-servers'
import { Route as SidebarLayoutSettingsProjectGuardrailsRouteImport } from './routes/_sidebar-layout.settings.project.guardrails'
import { Route as SidebarLayoutSettingsProjectAgentRouteImport } from './routes/_sidebar-layout.settings.project.agent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutSettingsRoute = SidebarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutRoute = SidebarLayoutChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutSettingsIndexRoute =
  SidebarLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutChatLayoutIndexRoute =
  SidebarLayoutChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSettingsUsageRoute =
  SidebarLayoutSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsProjectsRoute =
  SidebarLayoutSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsProjectRoute =
  SidebarLayoutSettingsProjectRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsMemoryRoute =
  SidebarLayoutSettingsMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsGeneralRoute =
  SidebarLayoutSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsAnalyticsRoute =
  SidebarLayoutSettingsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutChatLayoutChatIdRoute =
  SidebarLayoutChatLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSettingsProjectIndexRoute =
  SidebarLayoutSettingsProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectWorkflowRoute =
  SidebarLayoutSettingsProjectWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectTeamRoute =
  SidebarLayoutSettingsProjectTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectSlackRoute =
  SidebarLayoutSettingsProjectSlackRouteImport.update({
    id: '/slack',
    path: '/slack',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectModelsRoute =
  SidebarLayoutSettingsProjectModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMcpServersRoute =
  SidebarLayoutSettingsProjectMcpServersRouteImport.update({
    id: '/mcp-servers',
    path: '/mcp-servers',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectGuardrailsRoute =
  SidebarLayoutSettingsProjectGuardrailsRouteImport.update({
    id: '/guardrails',
    path: '/guardrails',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectAgentRoute =
  SidebarLayoutSettingsProjectAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/settings/analytics': typeof SidebarLayoutSettingsAnalyticsRoute
  '/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/settings/projects': typeof SidebarLayoutSettingsProjectsRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/guardrails': typeof SidebarLayoutSettingsProjectGuardrailsRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/workflow': typeof SidebarLayoutSettingsProjectWorkflowRoute
  '/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/settings/analytics': typeof SidebarLayoutSettingsAnalyticsRoute
  '/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/projects': typeof SidebarLayoutSettingsProjectsRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/settings': typeof SidebarLayoutSettingsIndexRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/guardrails': typeof SidebarLayoutSettingsProjectGuardrailsRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/workflow': typeof SidebarLayoutSettingsProjectWorkflowRoute
  '/settings/project': typeof SidebarLayoutSettingsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_sidebar-layout/_chat-layout': typeof SidebarLayoutChatLayoutRouteWithChildren
  '/_sidebar-layout/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/_sidebar-layout/_chat-layout/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/_sidebar-layout/settings/analytics': typeof SidebarLayoutSettingsAnalyticsRoute
  '/_sidebar-layout/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/_sidebar-layout/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/_sidebar-layout/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/_sidebar-layout/settings/projects': typeof SidebarLayoutSettingsProjectsRoute
  '/_sidebar-layout/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/_sidebar-layout/_chat-layout/': typeof SidebarLayoutChatLayoutIndexRoute
  '/_sidebar-layout/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/_sidebar-layout/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/_sidebar-layout/settings/project/guardrails': typeof SidebarLayoutSettingsProjectGuardrailsRoute
  '/_sidebar-layout/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/_sidebar-layout/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/_sidebar-layout/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/_sidebar-layout/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/_sidebar-layout/settings/project/workflow': typeof SidebarLayoutSettingsProjectWorkflowRoute
  '/_sidebar-layout/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/$chatId'
    | '/settings/analytics'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/project'
    | '/settings/projects'
    | '/settings/usage'
    | '/settings/'
    | '/settings/project/agent'
    | '/settings/project/guardrails'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/workflow'
    | '/settings/project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/$chatId'
    | '/settings/analytics'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/projects'
    | '/settings/usage'
    | '/settings'
    | '/settings/project/agent'
    | '/settings/project/guardrails'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/workflow'
    | '/settings/project'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/login'
    | '/signup'
    | '/_sidebar-layout/_chat-layout'
    | '/_sidebar-layout/settings'
    | '/_sidebar-layout/_chat-layout/$chatId'
    | '/_sidebar-layout/settings/analytics'
    | '/_sidebar-layout/settings/general'
    | '/_sidebar-layout/settings/memory'
    | '/_sidebar-layout/settings/project'
    | '/_sidebar-layout/settings/projects'
    | '/_sidebar-layout/settings/usage'
    | '/_sidebar-layout/_chat-layout/'
    | '/_sidebar-layout/settings/'
    | '/_sidebar-layout/settings/project/agent'
    | '/_sidebar-layout/settings/project/guardrails'
    | '/_sidebar-layout/settings/project/mcp-servers'
    | '/_sidebar-layout/settings/project/models'
    | '/_sidebar-layout/settings/project/slack'
    | '/_sidebar-layout/settings/project/team'
    | '/_sidebar-layout/settings/project/workflow'
    | '/_sidebar-layout/settings/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/settings': {
      id: '/_sidebar-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarLayoutSettingsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout': {
      id: '/_sidebar-layout/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/': {
      id: '/_sidebar-layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SidebarLayoutSettingsIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/_chat-layout/': {
      id: '/_sidebar-layout/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/settings/usage': {
      id: '/_sidebar-layout/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SidebarLayoutSettingsUsageRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/projects': {
      id: '/_sidebar-layout/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectsRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/project': {
      id: '/_sidebar-layout/settings/project'
      path: '/project'
      fullPath: '/settings/project'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/memory': {
      id: '/_sidebar-layout/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SidebarLayoutSettingsMemoryRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/general': {
      id: '/_sidebar-layout/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SidebarLayoutSettingsGeneralRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/analytics': {
      id: '/_sidebar-layout/settings/analytics'
      path: '/analytics'
      fullPath: '/settings/analytics'
      preLoaderRoute: typeof SidebarLayoutSettingsAnalyticsRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/_chat-layout/$chatId': {
      id: '/_sidebar-layout/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof SidebarLayoutChatLayoutChatIdRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/settings/project/': {
      id: '/_sidebar-layout/settings/project/'
      path: '/'
      fullPath: '/settings/project/'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/workflow': {
      id: '/_sidebar-layout/settings/project/workflow'
      path: '/workflow'
      fullPath: '/settings/project/workflow'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectWorkflowRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/team': {
      id: '/_sidebar-layout/settings/project/team'
      path: '/team'
      fullPath: '/settings/project/team'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTeamRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/slack': {
      id: '/_sidebar-layout/settings/project/slack'
      path: '/slack'
      fullPath: '/settings/project/slack'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectSlackRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/models': {
      id: '/_sidebar-layout/settings/project/models'
      path: '/models'
      fullPath: '/settings/project/models'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectModelsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mcp-servers': {
      id: '/_sidebar-layout/settings/project/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/settings/project/mcp-servers'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMcpServersRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/guardrails': {
      id: '/_sidebar-layout/settings/project/guardrails'
      path: '/guardrails'
      fullPath: '/settings/project/guardrails'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectGuardrailsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/agent': {
      id: '/_sidebar-layout/settings/project/agent'
      path: '/agent'
      fullPath: '/settings/project/agent'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectAgentRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
  }
}

interface SidebarLayoutChatLayoutRouteChildren {
  SidebarLayoutChatLayoutChatIdRoute: typeof SidebarLayoutChatLayoutChatIdRoute
  SidebarLayoutChatLayoutIndexRoute: typeof SidebarLayoutChatLayoutIndexRoute
}

const SidebarLayoutChatLayoutRouteChildren: SidebarLayoutChatLayoutRouteChildren =
  {
    SidebarLayoutChatLayoutChatIdRoute: SidebarLayoutChatLayoutChatIdRoute,
    SidebarLayoutChatLayoutIndexRoute: SidebarLayoutChatLayoutIndexRoute,
  }

const SidebarLayoutChatLayoutRouteWithChildren =
  SidebarLayoutChatLayoutRoute._addFileChildren(
    SidebarLayoutChatLayoutRouteChildren,
  )

interface SidebarLayoutSettingsProjectRouteChildren {
  SidebarLayoutSettingsProjectAgentRoute: typeof SidebarLayoutSettingsProjectAgentRoute
  SidebarLayoutSettingsProjectGuardrailsRoute: typeof SidebarLayoutSettingsProjectGuardrailsRoute
  SidebarLayoutSettingsProjectMcpServersRoute: typeof SidebarLayoutSettingsProjectMcpServersRoute
  SidebarLayoutSettingsProjectModelsRoute: typeof SidebarLayoutSettingsProjectModelsRoute
  SidebarLayoutSettingsProjectSlackRoute: typeof SidebarLayoutSettingsProjectSlackRoute
  SidebarLayoutSettingsProjectTeamRoute: typeof SidebarLayoutSettingsProjectTeamRoute
  SidebarLayoutSettingsProjectWorkflowRoute: typeof SidebarLayoutSettingsProjectWorkflowRoute
  SidebarLayoutSettingsProjectIndexRoute: typeof SidebarLayoutSettingsProjectIndexRoute
}

const SidebarLayoutSettingsProjectRouteChildren: SidebarLayoutSettingsProjectRouteChildren =
  {
    SidebarLayoutSettingsProjectAgentRoute:
      SidebarLayoutSettingsProjectAgentRoute,
    SidebarLayoutSettingsProjectGuardrailsRoute:
      SidebarLayoutSettingsProjectGuardrailsRoute,
    SidebarLayoutSettingsProjectMcpServersRoute:
      SidebarLayoutSettingsProjectMcpServersRoute,
    SidebarLayoutSettingsProjectModelsRoute:
      SidebarLayoutSettingsProjectModelsRoute,
    SidebarLayoutSettingsProjectSlackRoute:
      SidebarLayoutSettingsProjectSlackRoute,
    SidebarLayoutSettingsProjectTeamRoute:
      SidebarLayoutSettingsProjectTeamRoute,
    SidebarLayoutSettingsProjectWorkflowRoute:
      SidebarLayoutSettingsProjectWorkflowRoute,
    SidebarLayoutSettingsProjectIndexRoute:
      SidebarLayoutSettingsProjectIndexRoute,
  }

const SidebarLayoutSettingsProjectRouteWithChildren =
  SidebarLayoutSettingsProjectRoute._addFileChildren(
    SidebarLayoutSettingsProjectRouteChildren,
  )

interface SidebarLayoutSettingsRouteChildren {
  SidebarLayoutSettingsAnalyticsRoute: typeof SidebarLayoutSettingsAnalyticsRoute
  SidebarLayoutSettingsGeneralRoute: typeof SidebarLayoutSettingsGeneralRoute
  SidebarLayoutSettingsMemoryRoute: typeof SidebarLayoutSettingsMemoryRoute
  SidebarLayoutSettingsProjectRoute: typeof SidebarLayoutSettingsProjectRouteWithChildren
  SidebarLayoutSettingsProjectsRoute: typeof SidebarLayoutSettingsProjectsRoute
  SidebarLayoutSettingsUsageRoute: typeof SidebarLayoutSettingsUsageRoute
  SidebarLayoutSettingsIndexRoute: typeof SidebarLayoutSettingsIndexRoute
}

const SidebarLayoutSettingsRouteChildren: SidebarLayoutSettingsRouteChildren = {
  SidebarLayoutSettingsAnalyticsRoute: SidebarLayoutSettingsAnalyticsRoute,
  SidebarLayoutSettingsGeneralRoute: SidebarLayoutSettingsGeneralRoute,
  SidebarLayoutSettingsMemoryRoute: SidebarLayoutSettingsMemoryRoute,
  SidebarLayoutSettingsProjectRoute:
    SidebarLayoutSettingsProjectRouteWithChildren,
  SidebarLayoutSettingsProjectsRoute: SidebarLayoutSettingsProjectsRoute,
  SidebarLayoutSettingsUsageRoute: SidebarLayoutSettingsUsageRoute,
  SidebarLayoutSettingsIndexRoute: SidebarLayoutSettingsIndexRoute,
}

const SidebarLayoutSettingsRouteWithChildren =
  SidebarLayoutSettingsRoute._addFileChildren(
    SidebarLayoutSettingsRouteChildren,
  )

interface SidebarLayoutRouteChildren {
  SidebarLayoutChatLayoutRoute: typeof SidebarLayoutChatLayoutRouteWithChildren
  SidebarLayoutSettingsRoute: typeof SidebarLayoutSettingsRouteWithChildren
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutChatLayoutRoute: SidebarLayoutChatLayoutRouteWithChildren,
  SidebarLayoutSettingsRoute: SidebarLayoutSettingsRouteWithChildren,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
